// AV I/O Reference — Device Database
// Edit this file to add or update devices.

const CATS = [
  { id: 'switcher', label: 'Video Switcher / Mixer',              pip: 'pip-switcher', tag: 'tag-switcher', icon: '🎛️' },
  { id: 'camera',   label: 'Camera',                              pip: 'pip-camera',   tag: 'tag-camera',   icon: '📷' },
  { id: 'capture',  label: 'Capture / Encoder',                   pip: 'pip-capture',  tag: 'tag-capture',  icon: '📼' },
  { id: 'audio',    label: 'Audio Interface',                     pip: 'pip-audio',    tag: 'tag-audio',    icon: '🎚️' },
  { id: 'mixer',    label: 'Audio Mixer',                         pip: 'pip-mixer',    tag: 'tag-mixer',    icon: '🎚️' },
  { id: 'recorder', label: 'Recorder / Monitor',                  pip: 'pip-monitor',  tag: 'tag-monitor',  icon: '⏺️' },
  { id: 'routing',  label: 'Distribution / Routing / Converter',  pip: 'pip-routing',  tag: 'tag-routing',  icon: '🔀' },
];

const CT = {
  hdmi:  { cls: 'ct-hdmi',  label: 'HDMI'  },
  sdi:   { cls: 'ct-sdi',   label: 'SDI'   },
  xlr:   { cls: 'ct-xlr',   label: 'XLR'   },
  trs:   { cls: 'ct-trs',   label: 'TRS'   },
  mini:  { cls: 'ct-mini',  label: '3.5mm' },
  rca:   { cls: 'ct-rca',   label: 'RCA'   },
  usb:   { cls: 'ct-usb',   label: 'USB'   },
  lan:   { cls: 'ct-lan',   label: 'LAN'   },
  bnc:   { cls: 'ct-bnc',   label: 'BNC'   },
  other: { cls: 'ct-other', label: '···'   },
};

const DEVICES = [

// ══════════════════════════════════════════════════════════════
// ROLAND — VIDEO SWITCHERS
// ══════════════════════════════════════════════════════════════

{ id: 'v-02hd-mkii', category: 'switcher', maker: 'Roland', model: 'V-02HD MK II', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',   count: '2×', detail: 'Up to 1080p60, both with scalers', type: 'hdmi' },
            { name: '3.5mm IN',  count: '2×', detail: 'Stereo mini-jack (A/B)', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT 1', count: '1×', detail: 'Program (PGM) — fixed', type: 'hdmi' },
            { name: 'HDMI OUT 2', count: '1×', detail: 'PGM / Preview 切替可 (up to 1080p60)', type: 'hdmi' },
            { name: 'USB 3.0',    count: '1×', detail: 'Streaming/recording to PC (up to 1080p60)', type: 'usb' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Entry-level 2-ch HDMI mixer. No SDI.', 'HDMI OUT 1 = PGM固定。HDMI OUT 2 = PGM/Preview切替可。', 'USB up to 1080p60 to PC (OBS/Zoom).', '10-ch audio mixer. Battery-powered option.'],
  signal:  ['HDMI IN ×2', '▶ V-02HD MK II', 'HDMI OUT ×2', 'USB (PC)'] },

{ id: 'v-1hd', category: 'switcher', maker: 'Roland', model: 'V-1HD', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',   count: '4×', detail: 'Up to 1080p60 (Ch4 with scaler only)', type: 'hdmi' },
            { name: 'RCA IN',    count: '1×', detail: 'Stereo RCA audio', type: 'rca' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT 1', count: '1×', detail: 'Program (PGM) — fixed', type: 'hdmi' },
            { name: 'HDMI OUT 2', count: '1×', detail: 'PGM / MultiView 切替可 (1080p60)', type: 'hdmi' },
            { name: 'RCA OUT',    count: '1×', detail: 'Stereo RCA audio', type: 'rca' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['No USB streaming. No SDI.', 'HDMI OUT 1 = PGM固定。HDMI OUT 2 = PGM/MultiView切替可（4分割）。', 'Ch1–3 must match system format; Ch4 has scaler.', '12-ch audio mixer.'],
  signal:  ['HDMI IN ×4', '▶ V-1HD', 'HDMI OUT ×2'] },

{ id: 'v-1hd-plus', category: 'switcher', maker: 'Roland', model: 'V-1HD+', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',   count: '4×', detail: 'Up to 1080p60 (Ch4 scaler)', type: 'hdmi' },
            { name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line (Ch1/Ch2)', type: 'xlr' },
            { name: 'RCA IN',    count: '1×', detail: 'Stereo RCA', type: 'rca' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT 1', count: '1×', detail: 'PGM / Preview / MultiView(10窓) — 独立選択可', type: 'hdmi' },
            { name: 'HDMI OUT 2', count: '1×', detail: 'PGM / Preview / MultiView(10窓) — 独立選択可 (メニュー表示対応)', type: 'hdmi' },
            { name: 'TRS OUT',    count: '1×', detail: 'Balanced 1/4" TRS stereo', type: 'trs' },
            { name: 'RCA OUT',    count: '1×', detail: 'Stereo RCA', type: 'rca' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['V-1HD with XLR inputs + TRS output.', 'HDMI OUT 1/2 ともに PGM / Preview / MultiView(10窓) を独立選択可。OUT 2 はメニューOSD表示も可。', '14-ch audio mixer. No USB streaming. No SDI.'],
  signal:  ['HDMI IN ×4', 'XLR IN ×2', '▶ V-1HD+', 'HDMI OUT ×2'] },

{ id: 'v-1sdi', category: 'switcher', maker: 'Roland', model: 'V-1SDI', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '3×', detail: 'Up to 1080p60 (Ch3 with scaler)', type: 'sdi' },
            { name: 'HDMI IN',   count: '2×', detail: 'Up to 1080p60 (Ch2 with scaler)', type: 'hdmi' },
            { name: 'RCA IN',    count: '1×', detail: 'Stereo RCA', type: 'rca' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' }],
  outputs: [{ name: '3G-SDI PGM', count: '1×', detail: 'Program (PGM) — fixed', type: 'sdi' },
            { name: '3G-SDI PVW', count: '1×', detail: 'PGM / Preview / MultiView 切替可', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: '「MULTI-VIEW」端子 — PGM / Preview / MultiView(4分割) 切替可', type: 'hdmi' },
            { name: 'TRS OUT',    count: '1×', detail: 'Balanced 1/4" TRS', type: 'trs' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['SDI-centric compact switcher — ENG/broadcast cameras.', '3×SDI + 2×HDMI in; 2×SDI + 1×HDMI out.', 'SDI OUT 1 = PGM固定。SDI OUT 2 = PGM/Preview/MultiView切替可。', 'HDMI OUT（MULTI-VIEW端子）= PGM/Preview/MultiView(4分割) 切替可。', 'No USB streaming.', '14-ch audio mixer.'],
  signal:  ['SDI IN ×3', 'HDMI IN ×2', '▶ V-1SDI', 'SDI OUT ×2', 'HDMI OUT'] },

{ id: 'v-1-4k', category: 'switcher', maker: 'Roland', model: 'V-1-4K', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '5×', detail: 'Up to 4K60p — all with scalers', type: 'hdmi' },
            { name: 'XLR IN',   count: '2×', detail: 'Balanced mic/line (Ch1/Ch2)', type: 'xlr' },
            { name: 'RCA IN',   count: '1×', detail: 'Stereo RCA', type: 'rca' }],
  outputs: [{ name: 'HDMI OUT',  count: '5×', detail: 'Program/Preview/AUX/MultiView/Thru (up to 4K60p)', type: 'hdmi' },
            { name: 'USB-C',     count: '1×', detail: 'Streaming/recording to PC (up to 4K60p)', type: 'usb' },
            { name: 'RCA OUT',   count: '1×', detail: 'Stereo RCA', type: 'rca' },
            { name: '3.5mm OUT', count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Compact 4K switcher. 4K60p processing.', '5× HDMI all with scalers. No SDI.', '14-ch audio. PTZ control (5 cams).'],
  signal:  ['HDMI IN ×5 (4K60p)', '▶ V-1-4K', 'HDMI OUT ×5', 'USB-C (4K Stream)'] },

{ id: 'v-8hd', category: 'switcher', maker: 'Roland', model: 'V-8HD', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN', count: '8×', detail: 'Up to 1080p60 (Ch7–8 with scalers)', type: 'hdmi' },
            { name: 'RCA IN',  count: '1×', detail: 'Stereo RCA', type: 'rca' }],
  outputs: [{ name: 'HDMI OUT 1', count: '1×', detail: 'Program (PGM) — fixed', type: 'hdmi' },
            { name: 'HDMI OUT 2', count: '1×', detail: 'PGM / Preview / MultiView 切替可 (1080p60)', type: 'hdmi' },
            { name: 'HDMI OUT 3', count: '1×', detail: 'MultiView専用 — 固定 1080p (外部モニター用)', type: 'hdmi' },
            { name: 'RCA OUT',    count: '1×', detail: 'Stereo RCA', type: 'rca' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['8× HDMI. No SDI. No USB streaming.', 'HDMI OUT 1 = PGM固定。HDMI OUT 2 = PGM/Preview/MultiView切替可。HDMI OUT 3 = MultiView専用（外部モニター接続用）。', '内蔵4.3" TFTディスプレイ（MultiView）はHDMI OUTとは別の独立した表示装置。', '18-ch audio. 24 scene memories.'],
  signal:  ['HDMI IN ×8', '▶ V-8HD', 'HDMI OUT ×3'] },

{ id: 'v-80hd', category: 'switcher', maker: 'Roland', model: 'V-80HD', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '4×', detail: 'With FRC (Ch5–8)', type: 'sdi' },
            { name: 'HDMI IN',   count: '4×', detail: '1080p60 + scalers (Ch1–2 also accept 4K downscale)', type: 'hdmi' },
            { name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line', type: 'xlr' },
            { name: 'RCA IN',    count: '1×', detail: 'Stereo RCA', type: 'rca' }],
  outputs: [{ name: 'HDMI OUT',    count: '3×', detail: 'Program/Sub-Prog/AUX (1080p60)', type: 'hdmi' },
            { name: '3G-SDI OUT',  count: '2×', detail: 'Program/Preview (3G-SDI)', type: 'sdi' },
            { name: 'USB-C',       count: '1×', detail: 'Streaming to PC (1080p60)', type: 'usb' },
            { name: 'LAN',         count: '1×', detail: 'RTMP/SRT direct streaming', type: 'lan' },
            { name: 'XLR OUT',     count: '2×', detail: 'Balanced stereo master', type: 'xlr' },
            { name: '3.5mm OUT',   count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['4×HDMI + 4×SDI. Ch1–2 HDMI accepts 4K (downscales to 1080p; or thru 4K).', 'LAN: RTMP/SRT. SD card recording.', '28-ch audio. 32 scenes/100 macros. PTZ (8 cams).'],
  signal:  ['SDI IN ×4', 'HDMI IN ×4', '▶ V-80HD', 'HDMI OUT ×3', 'SDI OUT ×2', 'USB-C', 'LAN (RTMP/SRT)'] },

{ id: 'v-160hd', category: 'switcher', maker: 'Roland', model: 'V-160HD', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '8×', detail: 'With FRC (Ch9–16)', type: 'sdi' },
            { name: 'HDMI IN',   count: '8×', detail: 'With scalers, Ch5–8 with 4× scalers', type: 'hdmi' },
            { name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line', type: 'xlr' },
            { name: 'RCA IN',    count: '1×', detail: 'Stereo RCA', type: 'rca' }],
  outputs: [{ name: 'HDMI OUT',   count: '3×', detail: 'Program/Sub-Prog/AUX (1080p60)', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '3×', detail: 'Program/Preview/AUX', type: 'sdi' },
            { name: 'USB-C',      count: '1×', detail: 'Streaming to PC (1080p60)', type: 'usb' },
            { name: 'XLR OUT',    count: '2×', detail: 'Balanced stereo master', type: 'xlr' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['16-ch flagship (8×HDMI + 8×SDI). No LAN direct streaming.', '40-ch audio. 30 scenes/100 macros. PTZ (16 cams).'],
  signal:  ['SDI IN ×8', 'HDMI IN ×8', '▶ V-160HD', 'HDMI OUT ×3', 'SDI OUT ×3', 'USB-C'] },

{ id: 'v-600uhd', category: 'switcher', maker: 'Roland', model: 'V-600UHD', icon: '🎛️',
  inputs:  [{ name: '12G-SDI IN', count: '2×', detail: 'Up to 4K60p with scalers', type: 'sdi' },
            { name: 'HDMI IN',    count: '4×', detail: 'Up to 4K60p with scalers', type: 'hdmi' },
            { name: 'RGB/Comp',   count: '1×', detail: 'RGB/Component input', type: 'other' },
            { name: 'XLR IN',     count: '2×', detail: 'Balanced mic/line', type: 'xlr' }],
  outputs: [{ name: 'HDMI OUT',     count: '4×', detail: 'Program/Preview/AUX/MultiView (4K60p)', type: 'hdmi' },
            { name: '12G-SDI OUT',  count: '1×', detail: 'Program (12G-SDI, 4K60p)', type: 'sdi' },
            { name: 'XLR OUT',      count: '2×', detail: 'Balanced stereo master', type: 'xlr' },
            { name: '3.5mm OUT',    count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['4K/HDR multi-format. No USB/LAN streaming.', '16-ch audio. 64 scenes. PTZ (6 cams).'],
  signal:  ['HDMI IN ×4 (4K60p)', '12G-SDI IN ×2', '▶ V-600UHD', 'HDMI OUT ×4 (4K60p)', '12G-SDI OUT'] },

{ id: 'vr-4hd', category: 'switcher', maker: 'Roland', model: 'VR-4HD', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '4×', detail: 'Up to 1080p60 (Ch4 scaler)', type: 'hdmi' },
            { name: 'XLR IN',   count: '2×', detail: 'Balanced mic/line, phantom +48V', type: 'xlr' },
            { name: 'TRS IN',   count: '2×', detail: '1/4" TRS line/instrument', type: 'trs' },
            { name: 'RCA IN',   count: '1×', detail: 'Stereo RCA', type: 'rca' }],
  outputs: [{ name: 'HDMI OUT',  count: '3×', detail: 'Program ×2 + Preview/MultiView', type: 'hdmi' },
            { name: 'USB 3.0',   count: '1×', detail: 'USB-A streaming/recording to PC (up to 1080p30)', type: 'usb' },
            { name: 'TRS OUT',   count: '2×', detail: 'Balanced stereo master (L/R)', type: 'trs' },
            { name: '3.5mm OUT', count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['All-in-one with touchscreen multiview. No SDI.', 'USB output: up to 1080p30 (not 60p).', '18-ch audio with XLR/TRS faders.'],
  signal:  ['HDMI IN ×4', '▶ VR-4HD', 'HDMI OUT ×3', 'USB (PC 1080p30)'] },

{ id: 'vr-6hd', category: 'switcher', maker: 'Roland', model: 'VR-6HD', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',     count: '6×', detail: 'Up to 1080p60 with FRC and scaling', type: 'hdmi' },
            { name: 'XLR/TRS IN',  count: '2×', detail: 'Combo jack balanced mic/line', type: 'xlr' },
            { name: 'RCA IN',      count: '1×', detail: 'Stereo RCA', type: 'rca' }],
  outputs: [{ name: 'HDMI OUT',   count: '3×', detail: 'Program/Sub-Prog/Preview (1080p60)', type: 'hdmi' },
            { name: 'USB-C',      count: '1×', detail: 'Webcam streaming to PC', type: 'usb' },
            { name: 'LAN',        count: '1×', detail: 'RTMP/SRT direct streaming', type: 'lan' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['6×HDMI with LAN direct streaming. No SDI.', '28-ch audio. 32 scenes. PTZ (6 cams).'],
  signal:  ['HDMI IN ×6', '▶ VR-6HD', 'HDMI OUT ×3', 'USB-C', 'LAN (RTMP/SRT)'] },

{ id: 'vr-120hd', category: 'switcher', maker: 'Roland', model: 'VR-120HD', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '6×', detail: 'With FRC (Ch7–12)', type: 'sdi' },
            { name: 'HDMI IN',   count: '6×', detail: 'With scalers (Ch1–6)', type: 'hdmi' },
            { name: 'XLR/TRS IN',count: '6×', detail: 'Balanced mic/line combo jack (Ch A–F, phantom +48V)', type: 'xlr' },
            { name: 'RCA IN',    count: '4×', detail: 'Unbalanced stereo line-level (2 stereo pairs: Ch7/8 and Ch9/10)', type: 'rca' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT',   count: '3×', detail: 'Program/Preview/MultiView (1080p60)', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '3×', detail: 'Program/Preview/AUX', type: 'sdi' },
            { name: 'USB-C',      count: '1×', detail: 'Webcam streaming to PC', type: 'usb' },
            { name: 'LAN',        count: '1×', detail: 'RTMP/SRT direct streaming', type: 'lan' },
            { name: 'XLR OUT',    count: '2×', detail: 'Balanced stereo master (L/R)', type: 'xlr' },
            { name: 'RCA OUT',    count: '1×', detail: 'Unbalanced stereo line-level (1 stereo pair)', type: 'rca' },
            { name: '3.5mm OUT',  count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['12-ch flagship AV mixer (6×HDMI + 6×SDI).', '42-ch audio. 32 scenes/100 macros.', 'MultiView: up to 12-split. PTZ control.', 'RCA IN ×4: 2ステレオペア（Audio In 7/8、9/10）。RCA OUT ×1: ステレオ1系統。', 'XLR/TRS ×6: コンボジャック（Ch A–F、ファンタム +48V対応）。'],
  signal:  ['SDI IN ×6', 'HDMI IN ×6', '▶ VR-120HD', 'HDMI OUT ×3', 'SDI OUT ×3', 'USB-C', 'LAN (RTMP/SRT)'] },

{ id: 'sr-20hd', category: 'switcher', maker: 'Roland', model: 'SR-20HD', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',   count: '4×', detail: 'Up to 1080p60 with scalers', type: 'hdmi' },
            { name: '3.5mm IN',  count: '2×', detail: 'Stereo mini-jack (A/B)', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT',  count: '2×', detail: 'Program + Preview/MultiView', type: 'hdmi' },
            { name: 'USB-C',     count: '1×', detail: 'Streaming to PC (webcam)', type: 'usb' },
            { name: 'LAN',       count: '1×', detail: 'RTMP/SRT direct streaming', type: 'lan' },
            { name: '3.5mm OUT', count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Compact 4×HDMI with LAN streaming. No SDI.'],
  signal:  ['HDMI IN ×4', '▶ SR-20HD', 'HDMI OUT ×2', 'USB-C', 'LAN (RTMP/SRT)'] },

// ══════════════════════════════════════════════════════════════
// ATEM MINI SERIES
// ══════════════════════════════════════════════════════════════

{ id: 'atem-mini', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Mini', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '4×', detail: 'Standards converted, up to 1080p60', type: 'hdmi' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo headset input', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'Program (up to 1080p60)', type: 'hdmi' },
            { name: 'USB-C',    count: '1×', detail: 'Webcam output to PC', type: 'usb' }],
  notes:   ['Entry-level. No direct streaming, no recording, no MultiView.', 'No SDI I/O.'],
  signal:  ['HDMI IN ×4', '▶ ATEM Mini', 'HDMI OUT', 'USB-C (Webcam)'] },

{ id: 'atem-mini-pro', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Mini Pro', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '4×', detail: 'Standards converted, up to 1080p60', type: 'hdmi' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo headset input', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'Program / MultiView (1080p60)', type: 'hdmi' },
            { name: 'USB-C',    count: '1×', detail: 'Webcam + recording to USB disk', type: 'usb' },
            { name: 'LAN',      count: '1×', detail: 'RTMP/SRT direct streaming + control', type: 'lan' }],
  notes:   ['Adds RTMP/SRT LAN streaming vs base Mini.', 'Recording to USB disk (H.264). No SDI.'],
  signal:  ['HDMI IN ×4', '▶ ATEM Mini Pro', 'HDMI OUT', 'USB-C (Record)', 'LAN (RTMP/SRT)'] },

{ id: 'atem-mini-pro-iso', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Mini Pro ISO', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '4×', detail: 'Standards converted, up to 1080p60', type: 'hdmi' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo headset input', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'Program / MultiView (1080p60)', type: 'hdmi' },
            { name: 'USB-C',    count: '1×', detail: 'ISO recording (4 inputs + program = 5 streams)', type: 'usb' },
            { name: 'LAN',      count: '1×', detail: 'RTMP/SRT direct streaming', type: 'lan' }],
  notes:   ['ISO: 4 inputs + program simultaneously.', 'DaVinci Resolve project file export. No SDI.'],
  signal:  ['HDMI IN ×4', '▶ ATEM Mini Pro ISO', 'HDMI OUT', 'USB-C (ISO ×5)', 'LAN (RTMP/SRT)'] },

{ id: 'atem-mini-extreme', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Mini Extreme', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '8×', detail: 'Standards converted, up to 1080p60', type: 'hdmi' },
            { name: 'XLR IN',   count: '2×', detail: 'Balanced mic/line', type: 'xlr' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo headset', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '2×', detail: 'Program + MultiView (1080p60)', type: 'hdmi' },
            { name: 'USB-C',    count: '2×', detail: 'Webcam + recording', type: 'usb' },
            { name: 'LAN',      count: '1×', detail: 'RTMP/SRT streaming + control', type: 'lan' }],
  notes:   ['8× HDMI. 2× HDMI OUT. 4 Chroma Keyers. No SDI.'],
  signal:  ['HDMI IN ×8', '▶ ATEM Mini Extreme', 'HDMI OUT ×2', 'USB-C ×2', 'LAN'] },

{ id: 'atem-mini-extreme-iso', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Mini Extreme ISO', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '8×', detail: 'Standards converted, up to 1080p60', type: 'hdmi' },
            { name: 'XLR IN',   count: '2×', detail: 'Balanced mic/line', type: 'xlr' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo headset', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '2×', detail: 'Program + MultiView (1080p60)', type: 'hdmi' },
            { name: 'USB-C',    count: '2×', detail: 'ISO: 8 inputs + program', type: 'usb' },
            { name: 'LAN',      count: '1×', detail: 'RTMP/SRT + control', type: 'lan' }],
  notes:   ['ISO: all 8 inputs + program. DaVinci Resolve export. No SDI.'],
  signal:  ['HDMI IN ×8', '▶ ATEM Mini Extreme ISO', 'HDMI OUT ×2', 'USB-C ×2 (ISO)', 'LAN'] },

{ id: 'atem-mini-extreme-iso-g2', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Mini Extreme ISO G2', icon: '🎛️',
  inputs:  [{ name: 'HDMI IN',  count: '8×', detail: 'Standards converted, up to 1080p60', type: 'hdmi' },
            { name: 'XLR IN',   count: '2×', detail: 'Balanced mic/line', type: 'xlr' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo headset', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT',    count: '3×', detail: 'Program + MultiView + independent output', type: 'hdmi' },
            { name: 'USB-C',       count: '2×', detail: 'ISO recording (8 inputs + program)', type: 'usb' },
            { name: 'LAN (1G)',    count: '1×', detail: 'RTMP/SRT streaming + control', type: 'lan' },
            { name: 'LAN (10G)',   count: '1×', detail: '10G Ethernet — network storage recording', type: 'lan' },
            { name: 'Thunderbolt', count: '1×', detail: 'Thunderbolt — capture/playback to host', type: 'usb' }],
  notes:   ['New 2025. 3× HDMI OUT (upgraded from 2×). 10G LAN for storage.', 'CFexpress slot. Thunderbolt for host capture. No SDI.'],
  signal:  ['HDMI IN ×8', '▶ ATEM Mini Extreme ISO G2', 'HDMI OUT ×3', 'USB-C ×2 (ISO)', '10G LAN', 'Thunderbolt'] },

// ══════════════════════════════════════════════════════════════
// ATEM SDI SERIES
// ══════════════════════════════════════════════════════════════

{ id: 'atem-sdi', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM SDI', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '4×', detail: 'Standards converted 3G-SDI, up to 1080p60 (re-sync on all inputs)', type: 'sdi' },
            { name: '3.5mm IN',  count: '2×', detail: 'Unbalanced stereo mini-jack (mic plug-in power supported)', type: 'mini' }],
  outputs: [{ name: '3G-SDI OUT', count: '2×', detail: 'Program output (3G-SDI, up to 1080p60)', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'MultiView monitor output (up to 1080p60)', type: 'hdmi' },
            { name: 'USB-C',      count: '1×', detail: 'Webcam output to PC', type: 'usb' },
            { name: 'LAN',        count: '1×', detail: 'Ethernet — software control + panel connection', type: 'lan' }],
  notes:   ['SDI版ATEM Mini。4×3G-SDI入力、2×SDI出力 + HDMI MultiView出力。', 'No direct streaming, no recording (vs Pro ISO model).', '3.5mm ×2 analog audio inputs. Fairlight audio: EQ, compressor, gate, limiter.', '2× DVE, 4× Upstream Keyers, 2× Downstream Keyers.', 'Re-sync + standards conversion on all 4 SDI inputs.'],
  signal:  ['SDI IN ×4', '▶ ATEM SDI', 'SDI OUT ×2', 'HDMI OUT (MultiView)', 'USB-C (Webcam)'] },

{ id: 'atem-sdi-pro-iso', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM SDI Pro ISO', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '4×', detail: 'Standards converted 3G-SDI, up to 1080p60 (re-sync on all inputs)', type: 'sdi' },
            { name: '3.5mm IN',  count: '2×', detail: 'Unbalanced stereo mini-jack', type: 'mini' }],
  outputs: [{ name: '3G-SDI OUT', count: '2×', detail: 'Program output (3G-SDI, up to 1080p60)', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'MultiView monitor output', type: 'hdmi' },
            { name: 'USB-C',      count: '2×', detail: 'ISO recording (4 inputs + program = 5 streams) + webcam', type: 'usb' },
            { name: 'LAN',        count: '1×', detail: 'RTMP direct streaming + control', type: 'lan' }],
  notes:   ['ATEM SDI + ISO recording + RTMP streaming。', 'ISO: 4× SDI inputs + program (5 streams) simultaneously to USB disk (H.264).', 'DaVinci Resolve project file (.drp) saved for post editing.', 'RTMP direct streaming via LAN (no SRT on this model).', '2× DVE, 4× Upstream Keyers, 2× Downstream Keyers.'],
  signal:  ['SDI IN ×4', '▶ ATEM SDI Pro ISO', 'SDI OUT ×2', 'HDMI OUT (MultiView)', 'USB-C ×2 (ISO ×5)', 'LAN (RTMP)'] },

{ id: 'atem-sdi-extreme-iso', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM SDI Extreme ISO', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '8×', detail: 'Standards converted 3G-SDI, up to 1080p60 (re-sync + FRC on all inputs)', type: 'sdi' },
            { name: '3.5mm IN',  count: '2×', detail: 'Unbalanced stereo mini-jack', type: 'mini' }],
  outputs: [{ name: '3G-SDI OUT', count: '4×', detail: '4× SDI — Program/Preview/AUX assignable (3G-SDI)', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'MultiView monitor output (up to 16-split)', type: 'hdmi' },
            { name: 'USB-C',      count: '2×', detail: 'ISO recording (8 inputs + program = 9 streams)', type: 'usb' },
            { name: 'LAN',        count: '1×', detail: 'RTMP direct streaming + control', type: 'lan' }],
  notes:   ['ATEM SDI Pro ISOの2倍規模。8×SDI入力、4×SDI出力。', 'ISO: all 8 SDI inputs + program (9 streams) simultaneously.', 'DaVinci Resolve project file (.drp) saved.', '4× SDI outputs (vs 2× on Pro ISO) — more routing flexibility.', 'MultiView: up to 16-split including all 8 inputs + SuperSource.', '4× Upstream Keyers (Advanced Chroma), 2× Downstream Keyers, 2× DVE.', '11-input Fairlight audio mixer with EQ/compressor/gate/limiter.'],
  signal:  ['SDI IN ×8', '▶ ATEM SDI Extreme ISO', 'SDI OUT ×4', 'HDMI OUT (MultiView 16-split)', 'USB-C ×2 (ISO ×9)', 'LAN (RTMP)'] },

// ══════════════════════════════════════════════════════════════
// ATEM TELEVISION STUDIO
// ══════════════════════════════════════════════════════════════

{ id: 'atem-tv-studio-hd8', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Television Studio HD8', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '8×', detail: 'Standards converted 3G-SDI, up to 1080p60', type: 'sdi' }],
  outputs: [{ name: '3G-SDI OUT', count: '1×', detail: 'Program output', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'MultiView monitor output', type: 'hdmi' },
            { name: 'USB-C',      count: '2×', detail: 'Recording + streaming output', type: 'usb' },
            { name: 'LAN',        count: '4×', detail: '4-port Ethernet switch', type: 'lan' }],
  notes:   ['Built-in broadcast panel. 8×SDI only — no HDMI inputs.', 'RTMP/SRT built-in. Fairlight audio. Talkback.'],
  signal:  ['SDI IN ×8', '▶ ATEM TV Studio HD8', 'SDI OUT', 'HDMI OUT (MultiView)', 'USB-C ×2', 'LAN ×4'] },

{ id: 'atem-tv-studio-hd8-iso', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Television Studio HD8 ISO', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '8×', detail: 'Standards converted 3G-SDI, up to 1080p60', type: 'sdi' }],
  outputs: [{ name: '3G-SDI OUT', count: '1×', detail: 'Program output', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'MultiView', type: 'hdmi' },
            { name: 'USB-C',      count: '2×', detail: 'ISO recording (all 8 inputs + program)', type: 'usb' },
            { name: 'LAN',        count: '4×', detail: '4-port Ethernet switch', type: 'lan' }],
  notes:   ['HD8 + ISO recording of all 8 SDI inputs. DaVinci Resolve export.'],
  signal:  ['SDI IN ×8', '▶ ATEM TV Studio HD8 ISO', 'SDI OUT', 'USB-C ×2 (ISO)', 'LAN ×4'] },

{ id: 'atem-tv-studio-4k8', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Television Studio 4K8', icon: '🎛️',
  inputs:  [{ name: '12G-SDI IN', count: '8×', detail: 'Standards converted 12G-SDI, up to 4K60p', type: 'sdi' }],
  outputs: [{ name: '12G-SDI OUT', count: '10×', detail: '10× aux outputs (4K60p)', type: 'sdi' },
            { name: 'HDMI OUT',    count: '1×',  detail: 'MultiView monitor', type: 'hdmi' },
            { name: 'USB-C',       count: '2×',  detail: 'Recording + streaming', type: 'usb' },
            { name: 'LAN',         count: '4×',  detail: '4-port switch (includes 10G)', type: 'lan' }],
  notes:   ['4K version with 12G-SDI. 10× aux outputs.', 'Built-in panel + Fairlight + streaming.'],
  signal:  ['12G-SDI IN ×8', '▶ ATEM TV Studio 4K8', '12G-SDI AUX ×10', 'HDMI (MultiView)', 'USB-C ×2'] },

// ══════════════════════════════════════════════════════════════
// ATEM CONSTELLATION
// ══════════════════════════════════════════════════════════════

{ id: 'atem-const-hd', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Constellation HD', icon: '🎛️',
  inputs:  [{ name: '3G-SDI IN', count: '20×', detail: 'Standards converted 3G-SDI, up to 1080p60', type: 'sdi' }],
  outputs: [{ name: '3G-SDI OUT', count: '12×', detail: '12× aux outputs', type: 'sdi' },
            { name: 'USB-C',      count: '1×',  detail: 'Webcam/streaming output', type: 'usb' },
            { name: 'LAN',        count: '1×',  detail: 'Control + panel', type: 'lan' }],
  notes:   ['1 M/E. Requires ATEM Advanced Panel. 4 Keyers. Fairlight 48-ch.'],
  signal:  ['SDI IN ×20', '▶ ATEM Constellation HD', 'SDI AUX ×12', 'LAN (Panel)'] },

{ id: 'atem-const-4k-2me', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM 2M/E Constellation 4K', icon: '🎛️',
  inputs:  [{ name: '12G-SDI IN', count: '20×', detail: 'Standards converted 12G-SDI, up to 4K60p', type: 'sdi' }],
  outputs: [{ name: '12G-SDI OUT', count: '12×', detail: '12× aux outputs (4K60p)', type: 'sdi' },
            { name: 'LAN',         count: '1×',  detail: 'Control + panel', type: 'lan' }],
  notes:   ['2 M/E. 8 Keyers, SuperSource, 2× MultiView. Fairlight 48-ch.'],
  signal:  ['12G-SDI IN ×20 (4K60p)', '▶ ATEM 2M/E Constellation 4K', '12G-SDI AUX ×12'] },

{ id: 'atem-const-4k-4me', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM 4M/E Constellation 4K', icon: '🎛️',
  inputs:  [{ name: '12G-SDI IN', count: '40×', detail: 'Standards converted 12G-SDI, up to 4K60p', type: 'sdi' }],
  outputs: [{ name: '12G-SDI OUT', count: '24×', detail: '24× aux outputs', type: 'sdi' },
            { name: 'LAN',         count: '1×',  detail: 'Control + panel', type: 'lan' }],
  notes:   ['4 M/E. 16 Keyers, 2 SuperSource, 4 MultiViews. Fairlight 156-ch.'],
  signal:  ['12G-SDI IN ×40', '▶ ATEM 4M/E Constellation 4K', '12G-SDI AUX ×24'] },

{ id: 'atem-const-4k-4me-plus', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM 4M/E Constellation 4K Plus', icon: '🎛️',
  inputs:  [{ name: '12G-SDI IN', count: '80×', detail: 'Standards converted 12G-SDI, up to 4K60p', type: 'sdi' }],
  outputs: [{ name: '12G-SDI OUT', count: '48×', detail: '48× independent aux outputs', type: 'sdi' },
            { name: 'LAN',         count: '1×',  detail: 'Control + panel', type: 'lan' }],
  notes:   ['NAB 2025. Largest ATEM ever. 80× in / 48× out.', '16 Keyers, 4 SuperSource, 4 MultiViews. Fairlight 156-ch.'],
  signal:  ['12G-SDI IN ×80 (4K60p)', '▶ ATEM 4M/E Constellation 4K Plus', '12G-SDI AUX ×48'] },

// ATEM LEGACY
{ id: 'atem-extreme-iso', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM Extreme ISO', icon: '🎛️', legacy: true,
  inputs:  [{ name: 'HDMI IN',  count: '8×', detail: 'Standards converted, 1080p60', type: 'hdmi' },
            { name: 'XLR IN',   count: '2×', detail: 'Balanced mic/line', type: 'xlr' },
            { name: '3.5mm IN', count: '1×', detail: 'Stereo mini-jack', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '2×', detail: 'Program + MultiView', type: 'hdmi' },
            { name: 'USB-C',    count: '1×', detail: 'ISO recording', type: 'usb' },
            { name: 'LAN',      count: '1×', detail: 'RTMP/SRT + control', type: 'lan' }],
  notes:   ['ISO: all 8 inputs + program. DaVinci export. No SDI.'],
  signal:  ['HDMI IN ×8', '▶ ATEM Extreme ISO', 'HDMI OUT ×2', 'USB-C (ISO)', 'LAN'] },

{ id: 'atem-2me-production-4k', category: 'switcher', maker: 'Blackmagic Design', model: 'ATEM 2M/E Production Studio 4K', icon: '🎛️', legacy: true,
  inputs:  [{ name: '3G-SDI IN', count: '10×', detail: '3G-SDI, up to 1080p60', type: 'sdi' },
            { name: 'HDMI IN',   count: '10×', detail: 'Up to 4K30p', type: 'hdmi' }],
  outputs: [{ name: '3G-SDI OUT', count: '6×', detail: '6× aux/program', type: 'sdi' },
            { name: 'HDMI OUT',   count: '2×', detail: 'Program + MultiView', type: 'hdmi' },
            { name: 'LAN',        count: '1×', detail: 'Panel + software', type: 'lan' }],
  notes:   ['Legacy 2M/E. 10×SDI + 10×HDMI. Requires hardware panel.', 'No streaming. No ISO.'],
  signal:  ['SDI IN ×10', 'HDMI IN ×10', '▶ ATEM 2M/E Production Studio 4K', 'SDI OUT ×6', 'HDMI OUT ×2'] },

// ══════════════════════════════════════════════════════════════
// SONY — Cinema Line (current)
// ══════════════════════════════════════════════════════════════

{ id: 'sony-venice2', category: 'camera', maker: 'Sony', model: 'VENICE 2 (CineAlta)', icon: '📷',
  inputs:  [{ name: 'Multi Acc', count: '1×', detail: 'Multi Access Port — XDCA-Venice extension unit', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Headphone/monitoring (dual purpose)', type: 'mini' }],
  outputs: [{ name: '3G-SDI OUT', count: '2×', detail: '3G-SDI — monitoring / external record output', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — monitoring output', type: 'hdmi' },
            { name: 'USB-C',      count: '1×', detail: 'File transfer / firmware', type: 'usb' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone monitoring', type: 'mini' }],
  notes:   ['Flagship CineAlta. Full-frame 8.6K sensor (or S35 crop).', 'RAW output via 3G-SDI ×2 or via XDCA-Venice extension.', 'Records X-OCN (Original Camera Negative) and XAVC internally (SxS media).', 'S-Cinetone / S-Log3 / Venice Look on output.', 'Genlock input via multi-connector.'],
  signal:  ['Lens (FF 8.6K / S35)', '▶ VENICE 2', 'SDI OUT ×2 (RAW/Monitor)', 'HDMI OUT (Monitor)'] },

{ id: 'sony-burano', category: 'camera', maker: 'Sony', model: 'BURANO (CineAlta)', icon: '📷',
  inputs:  [{ name: 'Multi Acc', count: '1×', detail: 'Multi Access Port', type: 'other' },
            { name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: '3G-SDI OUT', count: '2×', detail: '3G-SDI — monitoring + RAW output', type: 'sdi' },
            { name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — monitoring', type: 'hdmi' },
            { name: 'USB-C',      count: '1×', detail: 'File transfer', type: 'usb' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['8K full-frame CineAlta in S35/handheld form. PL + E mount.', 'X-OCN XT/ST/LT + XAVC. Built-in 8-stop electronic ND.', 'SDI RAW output; HDMI monitoring.', 'XLR audio built-in (no handle required).', 'v2.0 (2025): 3.8K FF crop up to 120fps, 1.8× de-squeeze, tally via LAN.'],
  signal:  ['Lens (FF 8K / S35)', '▶ BURANO', 'SDI OUT ×2 (RAW/Monitor)', 'HDMI OUT (Monitor)'] },

{ id: 'sony-fx9', category: 'camera', maker: 'Sony', model: 'PXW-FX9', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (Ch1/Ch2)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: 'HDMI IN',    count: '1×', detail: 'HDMI Type-A (TC sync input)', type: 'hdmi' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60 (RAW via XDCA-FX9)', type: 'sdi' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: 'Genlock',    count: '1×', detail: 'BNC genlock reference input', type: 'bnc' }],
  notes:   ['Full-frame 6K sensor. Cinema Line flagship below VENICE.', 'HDMI: 4K60p 4:2:2 10-bit. SDI: HD native; RAW via XDCA-FX9 extension.', 'Genlock BNC — unique to FX9 in Cinema Line.', 'XDCA-FX9 adds 12G-SDI RAW, AES/EBU audio, and timecode expansion.', 'S-Cinetone / S-Log3 / Flexible ISO (800/4000).'],
  signal:  ['Lens (FF 6K)', '▶ PXW-FX9', 'HDMI OUT (4K60p)', 'SDI OUT (RAW via XDCA-FX9)'] },

{ id: 'sony-fx6', category: 'camera', maker: 'Sony', model: 'ILME-FX6', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (via XLR handle)', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — up to 4K120p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — RAW output (BNC)', type: 'sdi' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',      count: '1×', detail: 'File transfer', type: 'usb' }],
  notes:   ['Full-frame 12.1MP. Compact cinema body.', 'HDMI: up to 4K120p 4:2:2 10-bit. SDI: RAW output (BNC on body).', 'S-Cinetone / S-Log3 / Cine EI / Flexible ISO (800/12800).', 'v6.0 (2026): SDI RAW → Blackmagic RAW support.'],
  signal:  ['Lens (FF)', '▶ ILME-FX6', 'HDMI OUT (4K120p 10-bit)', 'SDI OUT (RAW)'] },

{ id: 'sony-fx3', category: 'camera', maker: 'Sony', model: 'ILME-FX3', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe (XLR Handle for XLR)', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'File transfer / tethering', type: 'usb' }],
  notes:   ['Full-frame. Most compact Cinema Line body.', 'HDMI: 4K60p 4:2:2 10-bit. No SDI natively.', 'v7.0 (Sep 2025): HDMI RAW → Blackmagic RAW, BIG6 menu, 1.5× anamorphic.', 'S-Cinetone / S-Log3 / Cine EI mode.'],
  signal:  ['Lens (FF)', '▶ ILME-FX3', 'HDMI OUT (4K60p 10-bit)'] },

{ id: 'sony-fx30', category: 'camera', maker: 'Sony', model: 'ILME-FX30', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'File transfer', type: 'usb' }],
  notes:   ['APS-C (Super 35) Cinema Line. Same HDMI output capability as FX3.', 'No SDI. No internal ND.', 'v6.0 (Sep 2025): HDMI RAW, BIG6 menu, 1.5× anamorphic.'],
  signal:  ['Lens (APS-C / S35)', '▶ ILME-FX30', 'HDMI OUT (4K60p 10-bit)'] },

{ id: 'sony-fr7', category: 'camera', maker: 'Sony', model: 'ILME-FR7 (PTZ)', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: 'LAN',        count: '1×', detail: 'Ethernet — control + IP streaming', type: 'lan' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — up to 4K60p', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Full-frame Cinema Line PTZ camera. E-mount.', 'Pan/tilt/zoom remotely via LAN or IP.', 'S-Cinetone / S-Log3 / 4K60p. HDMI + SDI simultaneous.'],
  signal:  ['E-Mount Lens (FF PTZ)', '▶ ILME-FR7', 'HDMI OUT (4K60p)', 'SDI OUT (1080p60)', 'LAN (IP Control)'] },

// ══════════════════════════════════════════════════════════════
// SONY — XDCAM
// ══════════════════════════════════════════════════════════════

{ id: 'sony-pxw-z200', category: 'camera', maker: 'Sony', model: 'PXW-Z200', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (Ch1/Ch2)', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack (Ch3/Ch4)', type: 'mini' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI Type-A — up to 4K60p', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '1×', detail: '12G/6G/3G-SDI — up to 4K60p (with TC)', type: 'sdi' },
            { name: 'TC (BNC)',    count: '1×', detail: 'Timecode IN/OUT (BNC)', type: 'bnc' },
            { name: '3.5mm',       count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',       count: '1×', detail: 'File transfer / streaming', type: 'usb' },
            { name: 'LAN',         count: '1×', detail: 'Ethernet — RTMP/SRT streaming + FTP', type: 'lan' }],
  notes:   ['2024 flagship XDCAM. 1" Exmor RS, 20× zoom, AI-AF.', '12G-SDI OUT: 4K60p single cable. HDMI + SDI simultaneous.', 'LAN: RTMP/SRT direct streaming. Dual CFexpress Type A / SD slots.', 'XAVC HS / XAVC S / XAVC SI. BIONZ XR + AI unit.'],
  signal:  ['Lens (1" 20×)', '▶ PXW-Z200', 'HDMI OUT (4K60p)', '12G-SDI OUT (4K60p)', 'LAN (RTMP/SRT)'] },

{ id: 'sony-pxw-z280', category: 'camera', maker: 'Sony', model: 'PXW-Z280', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (Ch1/Ch2)', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack (Ch3/Ch4)', type: 'mini' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['3× 1/2" Exmor R CMOS. Broadcast 4K ENG.', 'HDMI: 4K30p. SDI: HD only (1080p60).', 'HDMI + SDI simultaneous. XQD dual media.'],
  signal:  ['Lens (3×1/2")', '▶ PXW-Z280', 'HDMI OUT (4K30 / FHD60)', 'SDI OUT (FHD60)'] },

{ id: 'sony-pxw-z190', category: 'camera', maker: 'Sony', model: 'PXW-Z190', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '3×', detail: 'Ch1/Ch2 (front), Ch3 (side) — mic/line/AES/EBU, +48V', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['3× 1/3" Exmor R ENG camera. 25× zoom.', 'HDMI + SDI simultaneous. SDI: HD only.', 'AES/EBU digital on XLR Ch1/Ch2.'],
  signal:  ['Lens (3×1/3")', '▶ PXW-Z190', 'HDMI OUT (4K30 / FHD60)', 'SDI OUT (FHD60)'] },

{ id: 'sony-pxw-z90', category: 'camera', maker: 'Sony', model: 'PXW-Z90V', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — 4K30p or 1080p59.94', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — 1080p59.94 / 1080i', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['1" Exmor RS. 12× zoom.', 'HDMI: 4K30 or FHD60. SDI: HD only. Both simultaneous.'],
  signal:  ['Lens (1")', '▶ PXW-Z90V', 'HDMI OUT (4K30 / FHD60)', 'SDI OUT (FHD60)'] },

{ id: 'sony-pxw-x400', category: 'camera', maker: 'Sony', model: 'PXW-X400', icon: '📷', legacy: true,
  inputs:  [{ name: 'XLR IN',    count: '3×', detail: 'Balanced mic/line, phantom +48V (front ×2, side ×1)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Legacy shoulder-mount ENG XDCAM. 3× 2/3" CMOS.', 'XAVC / MPEG HD / IMX recording. Interchangeable lens (1/3" bayonet).'],
  signal:  ['B4 Lens (3×2/3")', '▶ PXW-X400', 'HDMI OUT (FHD60)', 'SDI OUT (FHD60)'] },

{ id: 'sony-pxw-x500', category: 'camera', maker: 'Sony', model: 'PXW-X500', icon: '📷', legacy: true,
  inputs:  [{ name: 'XLR IN',  count: '4×', detail: 'Balanced mic/line, phantom +48V (×4 total)', type: 'xlr' },
            { name: 'HDMI IN', count: '1×', detail: 'HDMI (reference/return input)', type: 'hdmi' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '2×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Legacy large-format shoulder XDCAM. 3× 2/3" Exmor. B4 mount.', 'Dual 3G-SDI outputs. 4× XLR audio inputs.'],
  signal:  ['B4 Lens (3×2/3")', '▶ PXW-X500', 'HDMI OUT', 'SDI OUT ×2 (FHD60)'] },

{ id: 'sony-pxw-fs7', category: 'camera', maker: 'Sony', model: 'PXW-FS7 / FS7M2', icon: '📷', legacy: true,
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (front handle)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60 (RAW via XDCA-FS7)', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Super 35 XDCAM. E-mount. Popular for documentary/drama.', 'SDI RAW via XDCA-FS7 extension unit.', 'FS7M2 adds variable ND (internal).', 'XAVC / MPEG HD recording. XQD media.'],
  signal:  ['E-Mount Lens (S35)', '▶ PXW-FS7', 'HDMI OUT (4K30)', 'SDI OUT (FHD60)'] },

{ id: 'sony-pxw-fs5', category: 'camera', maker: 'Sony', model: 'PXW-FS5 / FS5M2', icon: '📷', legacy: true,
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (via handle)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI — up to 4K30p', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Super 35 XDCAM. Compact E-mount. Variable ND (FS5M2).', 'S-Log2/3 support. 120fps in Super 16 crop mode.'],
  signal:  ['E-Mount Lens (S35)', '▶ PXW-FS5', 'HDMI OUT (4K30)', 'SDI OUT (FHD60)'] },

// ══════════════════════════════════════════════════════════════
// SONY — NXCAM
// ══════════════════════════════════════════════════════════════

{ id: 'sony-hxr-nx800', category: 'camera', maker: 'Sony', model: 'HXR-NX800', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (Ch1/Ch2)', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack (Ch3/Ch4)', type: 'mini' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'File transfer / USB streaming', type: 'usb' },
            { name: 'LAN',      count: '1×', detail: 'Ethernet — RTMP/SRT streaming + FTP', type: 'lan' }],
  notes:   ['2024 NXCAM. 1" Exmor RS, 20× zoom, AI-AF, BIONZ XR.', 'No SDI output (vs Z200 XDCAM sibling).', 'LAN: RTMP/SRT direct streaming.', 'XAVC HS / XAVC S / XAVC SI. Dual CFexpress Type A / SD.'],
  signal:  ['Lens (1" 20×)', '▶ HXR-NX800', 'HDMI OUT (4K60p)', 'LAN (RTMP/SRT)'] },

{ id: 'sony-hxr-nx200', category: 'camera', maker: 'Sony', model: 'HXR-NX200', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (Ch1/Ch2)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['1" Exmor RS NXCAM. 12× zoom.', 'No SDI. HDMI: 4K30p max.'],
  signal:  ['Lens (1")', '▶ HXR-NX200', 'HDMI OUT (4K30p)'] },

{ id: 'sony-hxr-nx100', category: 'camera', maker: 'Sony', model: 'HXR-NX100', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (Ch1/Ch2)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['1/2.3" NXCAM. 12× zoom. Full HD only (no 4K).', 'No SDI. XAVC S / AVCHD recording.'],
  signal:  ['Lens (1/2.3")', '▶ HXR-NX100', 'HDMI OUT (FHD60)'] },

{ id: 'sony-hxr-nx80', category: 'camera', maker: 'Sony', model: 'HXR-NX80', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '2×', detail: 'Balanced mic/line, phantom +48V (via handle attachment)', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['1" Exmor RS NXCAM. 12× zoom. Compact.', 'No SDI. HDMI: 4K30p.'],
  signal:  ['Lens (1")', '▶ HXR-NX80', 'HDMI OUT (4K30p)'] },

{ id: 'sony-hxr-nx5r', category: 'camera', maker: 'Sony', model: 'HXR-NX5R', icon: '📷', legacy: true,
  inputs:  [{ name: 'XLR IN',    count: '3×', detail: 'Balanced mic/line, phantom +48V (front ×2, top ×1)', type: 'xlr' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' },
            { name: 'TC (BNC)',   count: '1×', detail: 'Timecode IN/OUT', type: 'bnc' },
            { name: '3.5mm',      count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Legacy 3× 1/2.8" NXCAM ENG. SDI + HDMI output.'],
  signal:  ['Lens (3×1/2.8")', '▶ HXR-NX5R', 'HDMI OUT (FHD60)', 'SDI OUT (FHD60)'] },

{ id: 'sony-hxr-mc88', category: 'camera', maker: 'Sony', model: 'HXR-MC88', icon: '📷',
  inputs:  [{ name: 'XLR IN',    count: '1×', detail: 'Balanced mic/line, phantom +48V (front)', type: 'xlr' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' },
            { name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['Entry NXCAM. 1× XLR (front). 1/2.8" CMOS. No 4K. No SDI.'],
  signal:  ['Lens (1/2.8")', '▶ HXR-MC88', 'HDMI OUT (FHD60)'] },

// ══════════════════════════════════════════════════════════════
// SONY — Consumer / Prosumer
// ══════════════════════════════════════════════════════════════

{ id: 'sony-fdr-ax700', category: 'camera', maker: 'Sony', model: 'FDR-AX700', icon: '📷', consumer: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K30p / 1080p120', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB',      count: '1×', detail: 'USB Micro-B (charging / file transfer)', type: 'usb' }],
  notes:   ['Consumer 4K. 1" Exmor RS. ZEISS Vario-Sonnar T* 12× zoom.', 'HDMI: 4K30p or 1080p120. No SDI. No XLR.', 'Useful for backup/B-cam in pro workflows.'],
  signal:  ['Lens (1" 12×)', '▶ FDR-AX700', 'HDMI OUT (4K30p / 1080p120)'] },

{ id: 'sony-fdr-ax100', category: 'camera', maker: 'Sony', model: 'FDR-AX100', icon: '📷', consumer: true, legacy: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB',      count: '1×', detail: 'USB Micro-B', type: 'usb' }],
  notes:   ['Legacy consumer 4K pioneer. 1" Exmor R. 12× zoom.', 'HDMI: 4K30p. No SDI. No XLR.'],
  signal:  ['Lens (1" 12×)', '▶ FDR-AX100', 'HDMI OUT (4K30p)'] },

{ id: 'sony-fdr-ax45a', category: 'camera', maker: 'Sony', model: 'FDR-AX45A', icon: '📷', consumer: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K30p', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB',      count: '1×', detail: 'USB Micro-B', type: 'usb' }],
  notes:   ['Consumer 4K. 1/2.5" CMOS. 20× zoom.', 'HDMI: 4K30p or 1080p60. No SDI. No XLR.'],
  signal:  ['Lens (1/2.5" 20×)', '▶ FDR-AX45A', 'HDMI OUT (4K30p)'] },

{ id: 'sony-hdr-cx900', category: 'camera', maker: 'Sony', model: 'HDR-CX900 / FDR-AX1', icon: '📷', consumer: true, legacy: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — 1080p60 (CX900) / 4K30p (AX1)', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB',      count: '1×', detail: 'USB Micro-B', type: 'usb' }],
  notes:   ['HDR-CX900: 1" sensor consumer flagship (FHD).', 'FDR-AX1: first Sony consumer 4K camcorder (4K XAVC S).', 'No SDI. No XLR.'],
  signal:  ['Lens (1")', '▶ CX900 / AX1', 'HDMI OUT'] },

// ══════════════════════════════════════════════════════════════
// SONY — Alpha Series
// ══════════════════════════════════════════════════════════════

{ id: 'sony-a1', category: 'camera', maker: 'Sony', model: 'α1 (ILCE-1)', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 8K30p / 4K120p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 Gen2 — file transfer / tethering', type: 'usb' }],
  notes:   ['50MP full-frame stacked BSI CMOS. Flagship Alpha.', 'HDMI: 8K30p RAW or 4K120p 4:2:2 10-bit.', 'No SDI. S-Cinetone / S-Log3 / HLG.'],
  signal:  ['E-Mount (FF 50MP)', '▶ α1', 'HDMI OUT (8K30 / 4K120p 10-bit)'] },

{ id: 'sony-a7s3', category: 'camera', maker: 'Sony', model: 'α7S III (ILCE-7SM3)', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K120p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 Gen2 file transfer', type: 'usb' }],
  notes:   ['12.1MP full-frame BSI. Low-light king.', 'HDMI: 4K120p 4:2:2 10-bit. No SDI.', 'S-Cinetone / S-Log3 / HLG. Dual CFexpress Type A / SD.'],
  signal:  ['E-Mount (FF 12MP)', '▶ α7S III', 'HDMI OUT (4K120p 10-bit)'] },

{ id: 'sony-a7s2', category: 'camera', maker: 'Sony', model: 'α7S II (ILCE-7SM2)', icon: '📷', legacy: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI — up to 4K30p / uncompressed 1080p', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB',      count: '1×', detail: 'Micro-B file transfer', type: 'usb' }],
  notes:   ['Legacy. 12.2MP FF. Excellent low-light.', 'HDMI: 4K30p or uncompressed 1080p60 external.', 'No SDI.'],
  signal:  ['E-Mount (FF 12MP)', '▶ α7S II', 'HDMI OUT (4K30p / 1080p60)'] },

{ id: 'sony-a7r5', category: 'camera', maker: 'Sony', model: 'α7R V (ILCE-7RM5)', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 8K25p / 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 Gen2', type: 'usb' }],
  notes:   ['61MP full-frame BSI. Resolution leader.', 'HDMI: 8K RAW or 4K60p 4:2:2 10-bit. No SDI.'],
  signal:  ['E-Mount (FF 61MP)', '▶ α7R V', 'HDMI OUT (8K25p / 4K60p 10-bit)'] },

{ id: 'sony-a7c2', category: 'camera', maker: 'Sony', model: 'α7C II (ILCE-7CM2)', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 Gen2', type: 'usb' }],
  notes:   ['33MP full-frame. Ultra-compact. S-Cinetone / S-Log3.', 'HDMI: 4K60p 4:2:2 10-bit. No SDI.'],
  signal:  ['E-Mount (FF 33MP)', '▶ α7C II', 'HDMI OUT (4K60p 10-bit)'] },

{ id: 'sony-a6700', category: 'camera', maker: 'Sony', model: 'α6700 (ILCE-6700)', icon: '📷',
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 Gen2', type: 'usb' }],
  notes:   ['26MP APS-C. AI-AF. Highest-spec current APS-C Alpha.', 'HDMI: 4K60p 4:2:2 10-bit. No SDI.'],
  signal:  ['E-Mount (APS-C 26MP)', '▶ α6700', 'HDMI OUT (4K60p 10-bit)'] },

{ id: 'sony-a6600', category: 'camera', maker: 'Sony', model: 'α6600 (ILCE-6600)', icon: '📷', legacy: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K30p / 1080p120', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB',      count: '1×', detail: 'Micro-B file transfer', type: 'usb' }],
  notes:   ['Legacy. 24.2MP APS-C. IBIS.', 'HDMI: 4K30p or 1080p120. No SDI.'],
  signal:  ['E-Mount (APS-C 24MP)', '▶ α6600', 'HDMI OUT (4K30p / 1080p120)'] },

{ id: 'sony-zv-e1', category: 'camera', maker: 'Sony', model: 'ZV-E1', icon: '📷', consumer: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 streaming / transfer', type: 'usb' }],
  notes:   ['12MP full-frame. Vlogging-oriented Cinema Line-adjacent.', 'HDMI: 4K60p 4:2:2 10-bit. S-Cinetone / S-Log3. No SDI.'],
  signal:  ['E-Mount (FF 12MP)', '▶ ZV-E1', 'HDMI OUT (4K60p 10-bit)'] },

{ id: 'sony-zv-e10m2', category: 'camera', maker: 'Sony', model: 'ZV-E10 II', icon: '📷', consumer: true,
  inputs:  [{ name: 'Multi Shoe', count: '1×', detail: 'Multi Interface Shoe', type: 'other' },
            { name: '3.5mm IN',  count: '1×', detail: 'Stereo mini-jack mic in', type: 'mini' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI Type-A — up to 4K60p / 4:2:2 10-bit', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' },
            { name: 'USB-C',    count: '1×', detail: 'USB 3.2 streaming / transfer', type: 'usb' }],
  notes:   ['26MP APS-C. Vlogging / streaming oriented.', 'HDMI: 4K60p 4:2:2 10-bit. No SDI.'],
  signal:  ['E-Mount (APS-C 26MP)', '▶ ZV-E10 II', 'HDMI OUT (4K60p 10-bit)'] },

// ══════════════════════════════════════════════════════════════
// CAPTURE / ENCODER
// ══════════════════════════════════════════════════════════════

{ id: 'cam-link-4k', category: 'capture', maker: 'Elgato', model: 'Cam Link 4K', icon: '📼',
  inputs:  [{ name: 'HDMI IN', count: '1×', detail: 'HDMI Type-A — up to 4K30p / 1080p60', type: 'hdmi' }],
  outputs: [{ name: 'USB-A',   count: '1×', detail: 'USB 3.0 — UVC device to host (OBS/Zoom)', type: 'usb' }],
  notes:   ['Plug-and-play UVC dongle. Max 4K30p or 1080p60 input.'],
  signal:  ['Camera HDMI', '▶ Cam Link 4K', 'USB-A', 'Host (OBS/Zoom)'] },

// ── AJA U-TAP ───────────────────────────────────────────────

{ id: 'aja-u-tap-hdmi', category: 'capture', maker: 'AJA', model: 'U-TAP HDMI', icon: '📼',
  inputs:  [{ name: 'HDMI IN', count: '1×', detail: 'HDMI 1.4a — up to 1080p60（HDCP非対応）', type: 'hdmi' }],
  outputs: [{ name: 'USB-B',   count: '1×', detail: 'USB 3.0 (USB 3.2 Gen1) — UVC/UACデバイスとしてホストへ', type: 'usb' }],
  notes:   ['バスパワー（USB給電）。ドライバ不要（UVC/UAC対応）。', 'Mac / Windows / Linux 対応。OBS・Zoom・Wirecast等と互換。', 'HDCP非対応。最大1080p60。'],
  signal:  ['Camera HDMI', '▶ U-TAP HDMI', 'USB 3.0 (Host)'] },

{ id: 'aja-u-tap-sdi', category: 'capture', maker: 'AJA', model: 'U-TAP SDI', icon: '📼',
  inputs:  [{ name: '3G-SDI IN', count: '1×', detail: '3G-SDI — up to 1080p60 (SMPTE-259/292/424)', type: 'sdi' }],
  outputs: [{ name: 'USB-B',      count: '1×', detail: 'USB 3.0 (USB 3.2 Gen1) — UVC/UAC host', type: 'usb' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI ループスルー出力', type: 'sdi' }],
  notes:   ['バスパワー（USB給電）。ドライバ不要。SDIループスルー出力あり。', 'Mac / Windows / Linux。最大1080p60。4:2:2 10-bit。'],
  signal:  ['Camera SDI', '▶ U-TAP SDI', 'USB 3.0 (Host)', 'SDI OUT (Loop)'] },

// ── Blackmagic UltraStudio ───────────────────────────────────

{ id: 'ultrastudio-recorder-3g', category: 'capture', maker: 'Blackmagic Design', model: 'UltraStudio Recorder 3G', icon: '📼',
  inputs:  [{ name: 'HDMI IN',   count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3G-SDI IN', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' }],
  outputs: [{ name: 'Thunderbolt 3', count: '1×', detail: 'TB3 — キャプチャ出力（ホスト接続）', type: 'usb' }],
  notes:   ['Thunderbolt 3必須（USB-C汎用不可）。バスパワー。', '3G-SDI + HDMI キャプチャ専用（プレイバック出力なし）。', '最大1080p60。DaVinci Resolve / Avid / Premiere Pro対応。'],
  signal:  ['Camera HDMI/SDI', '▶ UltraStudio Recorder 3G', 'Thunderbolt 3 (Host)'] },

{ id: 'ultrastudio-monitor-3g', category: 'capture', maker: 'Blackmagic Design', model: 'UltraStudio Monitor 3G', icon: '📼',
  inputs:  [{ name: 'Thunderbolt 3', count: '1×', detail: 'TB3 — ホストPC接続（プレイバック入力）', type: 'usb' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI — 最大1080p60（モニタリング出力）', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — 最大1080p60（モニタリング出力）', type: 'sdi' }],
  notes:   ['モニタリング出力専用（キャプチャ機能なし）。Thunderbolt 3必須。', 'DaVinci Resolve / Final Cut Pro / Premiere Proからの出力モニタリングに使用。', '最大1080p60。10-bit出力。'],
  signal:  ['Host PC (TB3)', '▶ UltraStudio Monitor 3G', 'HDMI OUT', 'SDI OUT'] },

{ id: 'ultrastudio-4k-mini', category: 'capture', maker: 'Blackmagic Design', model: 'UltraStudio 4K Mini', icon: '📼',
  inputs:  [{ name: 'HDMI IN',    count: '1×', detail: 'HDMI 2.0 — up to 4K60p', type: 'hdmi' },
            { name: '12G-SDI IN', count: '1×', detail: '12G-SDI — up to 4K60p', type: 'sdi' },
            { name: 'XLR IN',     count: '2×', detail: 'AES/EBU / バランスアナログ音声', type: 'xlr' }],
  outputs: [{ name: 'Thunderbolt 3', count: '2×', detail: 'TB3 — キャプチャ＋プレイバック', type: 'usb' },
            { name: 'HDMI OUT',      count: '1×', detail: 'HDMI 2.0 — モニタ/プレイバック出力', type: 'hdmi' },
            { name: '12G-SDI OUT',   count: '1×', detail: '12G-SDI — モニタ/同期出力', type: 'sdi' }],
  notes:   ['Thunderbolt 3必須（汎用USB-C不可）。4K60pキャプチャ＋プレイバック同時対応。', '前面LCD・マイク入力・ヘッドフォン出力・SDカードリーダー搭載。'],
  signal:  ['12G-SDI / HDMI IN', '▶ UltraStudio 4K Mini', 'Thunderbolt 3 (Host)', 'HDMI/SDI OUT'] },

// ── Blackmagic Intensity (PCIe) ──────────────────────────────

{ id: 'intensity-pro-4k', category: 'capture', maker: 'Blackmagic Design', model: 'Intensity Pro 4K', icon: '📼',
  inputs:  [{ name: 'HDMI IN',  count: '1×', detail: 'HDMI 2.0 — up to 4K30p / 1080p60', type: 'hdmi' },
            { name: 'コンポーネント IN', count: '1×', detail: 'アナログ コンポーネント/コンポジット入力', type: 'other' }],
  outputs: [{ name: 'PCIe',     count: '1×', detail: 'PCIe x4 — ホスト接続', type: 'usb' },
            { name: 'HDMI OUT',  count: '1×', detail: 'HDMI 2.0 — プレイバック/モニタ出力', type: 'hdmi' }],
  notes:   ['PCIeカード（デスクトップPC内蔵）。HDMI 2.0でUltra HD対応。', 'アナログ（コンポーネント/コンポジット）入出力あり。DaVinci Resolve対応。', '4K30p / 1080p60キャプチャ。'],
  signal:  ['HDMI IN / Analog IN', '▶ Intensity Pro 4K (PCIe)', 'Host PC', 'HDMI OUT'] },

// ── Blackmagic DeckLink (PCIe) ───────────────────────────────

{ id: 'decklink-mini-recorder-hd', category: 'capture', maker: 'Blackmagic Design', model: 'DeckLink Mini Recorder HD', icon: '📼',
  inputs:  [{ name: 'HDMI IN',   count: '1×', detail: 'HDMI 2.0 — up to 1080p60 / 2Kp60 DCI', type: 'hdmi' },
            { name: '3G-SDI IN', count: '1×', detail: '3G-SDI — up to 1080p60 / 2Kp60 DCI', type: 'sdi' }],
  outputs: [{ name: 'PCIe', count: '1×', detail: 'PCIe — ホスト接続（キャプチャ専用）', type: 'usb' }],
  notes:   ['PCIeカード（キャプチャ専用、プレイバック出力なし）。', 'HDMI 2.0 + 3G-SDI。最大1080p60 / 2Kp60 DCI。10-bit。'],
  signal:  ['HDMI / SDI Source', '▶ DeckLink Mini Recorder HD (PCIe)', 'Host PC'] },

{ id: 'decklink-mini-monitor-hd', category: 'capture', maker: 'Blackmagic Design', model: 'DeckLink Mini Monitor HD', icon: '📼',
  inputs:  [{ name: 'PCIe', count: '1×', detail: 'PCIe — ホスト接続（プレイバック専用）', type: 'usb' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI 2.0 — up to 1080p60 / HDR', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' }],
  notes:   ['PCIeカード（モニタリング出力専用、キャプチャなし）。', 'DaVinci Resolve / Final Cut Pro / Premiere Proの出力モニタリングに。HDR対応。'],
  signal:  ['Host PC (PCIe)', '▶ DeckLink Mini Monitor HD', 'HDMI OUT', 'SDI OUT'] },

{ id: 'decklink-quad-hdmi', category: 'capture', maker: 'Blackmagic Design', model: 'DeckLink Quad HDMI Recorder', icon: '📼',
  inputs:  [{ name: 'HDMI IN', count: '4×', detail: 'HDMI 2.0b — 各チャンネル最大4K60p（独立4系統）', type: 'hdmi' }],
  outputs: [{ name: 'PCIe', count: '1×', detail: 'PCIe x8 — ホスト接続（4ch同時キャプチャ）', type: 'usb' }],
  notes:   ['4系統HDMI同時キャプチャ専用PCIeカード（4枚分の機能を1枚で）。', '各入力独立：SD / HD / Ultra HD / 4K / PCフォーマット混在可。', 'マルチカムキャプチャ・ゲーム配信・ライブスイッチャー用途に最適。'],
  signal:  ['HDMI Sources ×4', '▶ DeckLink Quad HDMI (PCIe)', 'Host PC (4ch同時)'] },

{ id: 'decklink-duo-2', category: 'capture', maker: 'Blackmagic Design', model: 'DeckLink Duo 2', icon: '📼',
  inputs:  [{ name: '3G-SDI', count: '4×', detail: '3G-SDI — 各最大1080p60（キャプチャ or プレイバック 方向設定可）', type: 'sdi' }],
  outputs: [{ name: 'PCIe', count: '1×', detail: 'PCIe — ホスト接続（4ch 独立 SDI I/O）', type: 'usb' }],
  notes:   ['4系統3G-SDI PCIeカード。各コネクタをキャプチャ/プレイバック方向に個別設定可。', 'SD / HD 最大1080p60。マルチチャンネルSDI I/Oに最適。'],
  signal:  ['SDI Sources ×4', '▶ DeckLink Duo 2 (PCIe)', 'Host PC (4ch SDI I/O)'] },

// ══════════════════════════════════════════════════════════════
// AUDIO INTERFACE
// ══════════════════════════════════════════════════════════════

{ id: 'scarlett-2i2', category: 'audio', maker: 'Focusrite', model: 'Scarlett 2i2 (4th Gen)', icon: '🎚️',
  inputs:  [{ name: 'Combo IN', count: '2×', detail: 'XLR/TRS combo — mic/line/inst, +48V', type: 'xlr' }],
  outputs: [{ name: 'USB-C',    count: '1×', detail: 'USB-C — class-compliant interface', type: 'usb' },
            { name: 'TRS OUT',  count: '2×', detail: '1/4" TRS balanced monitor L/R', type: 'trs' },
            { name: 'Headphone',count: '1×', detail: '3.5mm stereo', type: 'mini' }],
  notes:   ['2-in/2-out. Bus powered. Up to 192kHz/24-bit.'],
  signal:  ['XLR IN ×2', '▶ Scarlett 2i2', 'USB-C', 'DAW Host'] },

// ══════════════════════════════════════════════════════════════
// AUDIO MIXER
// ══════════════════════════════════════════════════════════════

{ id: 'sq5', category: 'mixer', maker: 'Allen & Heath', model: 'SQ-5', icon: '🎚️',
  inputs:  [{ name: 'Mic/Line IN', count: '16×', detail: 'XLR/TRS combo (Ch1–16, phantom +48V)', type: 'xlr' },
            { name: 'ST IN',       count: '3×',  detail: '1/4" TRS stereo pairs', type: 'trs' },
            { name: 'AES/EBU IN',  count: '1×',  detail: 'Digital stereo input', type: 'xlr' },
            { name: 'USB-B',       count: '1×',  detail: '32ch multi-track playback', type: 'usb' }],
  outputs: [{ name: 'Mix OUT',     count: '12×', detail: 'XLR — Mixes/Auxes/Matrix', type: 'xlr' },
            { name: 'LR Main',     count: '1×',  detail: 'XLR balanced stereo master', type: 'xlr' },
            { name: 'AES/EBU OUT', count: '1×',  detail: 'Digital stereo output', type: 'xlr' },
            { name: 'USB-B',       count: '1×',  detail: '32ch multi-track recording', type: 'usb' },
            { name: 'Headphone',   count: '1×',  detail: '1/4" TRS', type: 'trs' }],
  notes:   ['48 processing ch. LAN app control. Expandable via SLink.'],
  signal:  ['Mic/Line ×16', '▶ SQ-5', 'XLR OUT ×12', 'USB Multitrack', 'LAN (Remote)'] },

// ══════════════════════════════════════════════════════════════
// YAMAHA — AUDIO MIXERS
// ══════════════════════════════════════════════════════════════

{ id: 'yamaha-mg10xuf', category: 'mixer', maker: 'Yamaha', model: 'MG10XUF', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '4×', detail: 'Mic/Line コンボジャック（Ch1–4、+48V）', type: 'xlr' },
            { name: 'TRS IN',       count: '2×', detail: 'Line入力 1/4" TRS（Ch5–6ステレオペア）', type: 'trs' },
            { name: 'RCA IN',       count: '2×', detail: 'ステレオRCA（Ch7–8）', type: 'rca' }],
  outputs: [{ name: 'XLR OUT',   count: '2×', detail: 'バランスXLR メインL/R', type: 'xlr' },
            { name: 'TRS OUT',   count: '2×', detail: '1/4" TRS モニターL/R', type: 'trs' },
            { name: 'USB-B',     count: '1×', detail: 'USB-B — 2ch録音/再生（USBオーディオIF）', type: 'usb' },
            { name: 'Headphone', count: '1×', detail: '3.5mm ヘッドフォン', type: 'mini' }],
  notes:   ['MGシリーズ10ch。USB録音・再生対応。Aux1系統。コンプ（Ch1–2）。'],
  signal:  ['Mic/Line ×4', 'RCA ×2', '▶ MG10XUF', 'XLR OUT L/R', 'USB (2ch)'] },

{ id: 'yamaha-mg16xu', category: 'mixer', maker: 'Yamaha', model: 'MG16XU', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '8×', detail: 'Mic/Line コンボジャック（Ch1–8、+48V）', type: 'xlr' },
            { name: 'TRS IN',       count: '4×', detail: 'Line 1/4" TRS（Ch9–12ステレオペア）', type: 'trs' },
            { name: 'RCA IN',       count: '4×', detail: 'ステレオRCA（Ch13–16、2ペア）', type: 'rca' }],
  outputs: [{ name: 'XLR OUT',   count: '2×', detail: 'バランスXLR メインL/R', type: 'xlr' },
            { name: 'TRS OUT',   count: '2×', detail: '1/4" TRS モニターL/R', type: 'trs' },
            { name: 'TRS AUX',   count: '2×', detail: '1/4" TRS Aux1/Aux2 送り出し', type: 'trs' },
            { name: 'USB-B',     count: '1×', detail: 'USB-B — 2ch録音/再生', type: 'usb' },
            { name: 'Headphone', count: '1×', detail: '3.5mm ヘッドフォン', type: 'mini' }],
  notes:   ['MGシリーズ16ch。USB録音・再生。Aux×2。コンプ（Ch1–8）、EQ。'],
  signal:  ['Mic ×8 / Line ×4 / RCA ×4', '▶ MG16XU', 'XLR OUT L/R', 'AUX×2', 'USB'] },

{ id: 'yamaha-01v96i', category: 'mixer', maker: 'Yamaha', model: '01V96i', icon: '🎚️',
  inputs:  [{ name: 'XLR IN',    count: '16×', detail: 'XLR/TRSコンボ（CH1–16、+48V）', type: 'xlr' },
            { name: 'TRS IN',    count: '4×',  detail: '1/4" TRS ライン入力（IN17–20）', type: 'trs' },
            { name: 'AES/EBU',   count: '1×',  detail: 'AES/EBUデジタル IN（Ch21–22）', type: 'xlr' },
            { name: 'USB-B',     count: '1×',  detail: 'USB-B — ステレオ録音/再生（USB Audio）', type: 'usb' },
            { name: 'Mini-YGDAI',count: '1×',  detail: 'Mini-YGDAIスロット — 拡張カード（最大16ch I/O）', type: 'other' }],
  outputs: [{ name: 'XLR OUT',   count: '16×', detail: 'XLR バランス出力（OMNI OUT 1–16）', type: 'xlr' },
            { name: 'AES/EBU',   count: '1×',  detail: 'AES/EBUデジタル OUT', type: 'xlr' },
            { name: 'USB-B',     count: '1×',  detail: 'USB-B — ステレオ再生', type: 'usb' },
            { name: 'Headphone', count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['32ch デジタルミキサー（旧世代）。Mini-YGDAIスロット×1でDante等に拡張可。', 'DAWコントロール機能（HUI/Mackie）。USB Audio 2.0。'],
  signal:  ['XLR IN ×16', 'YGDAI拡張', '▶ 01V96i', 'OMNI OUT ×16', 'AES/EBU'] },

{ id: 'yamaha-tf1', category: 'mixer', maker: 'Yamaha', model: 'TF1', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '16×', detail: 'Mic/Line コンボジャック（CH1–16、+48V）', type: 'xlr' },
            { name: 'USB-A',        count: '1×',  detail: 'USB-A — 再生（iPad接続兼用）', type: 'usb' },
            { name: 'USB-B',        count: '1×',  detail: 'USB-B — PC 34ch録音', type: 'usb' }],
  outputs: [{ name: 'XLR OUT',    count: '16×', detail: 'XLR バランス出力（OMNI 1–16）', type: 'xlr' },
            { name: 'USB-B',      count: '1×',  detail: 'USB-B — PC 34ch再生', type: 'usb' },
            { name: 'Headphone',  count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['TouchFlow Operation。16chアナログ入力、16chアナログ出力。', '40ミックスチャンネル。Aux×8、Stereo Bus。19インチラックマウント可（RK5014）。', 'Tio1608-D（Dante I/Oラック）×3台まで拡張可（別売NY64-Dカード要）。'],
  signal:  ['XLR IN ×16', '▶ TF1', 'OMNI OUT ×16', 'USB (34ch)'] },

{ id: 'yamaha-tf3', category: 'mixer', maker: 'Yamaha', model: 'TF3', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '24×', detail: 'Mic/Line コンボジャック（CH1–24、+48V）', type: 'xlr' },
            { name: 'USB-A',        count: '1×',  detail: 'USB-A — 再生', type: 'usb' },
            { name: 'USB-B',        count: '1×',  detail: 'USB-B — PC 34ch録音', type: 'usb' }],
  outputs: [{ name: 'XLR OUT',   count: '16×', detail: 'XLR バランス出力（OMNI 1–16）', type: 'xlr' },
            { name: 'USB-B',     count: '1×',  detail: 'USB-B — PC 34ch再生', type: 'usb' },
            { name: 'Headphone', count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['TouchFlow Operation。24chアナログ入力。TF1と同じ48ミックスチャンネル。', '25フェーダー（モーターライズ）。アナログ出力はTF1と同じ16ch。'],
  signal:  ['XLR IN ×24', '▶ TF3', 'OMNI OUT ×16', 'USB (34ch)'] },

{ id: 'yamaha-tf5', category: 'mixer', maker: 'Yamaha', model: 'TF5', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '32×', detail: 'Mic/Line コンボジャック（CH1–32、+48V）', type: 'xlr' },
            { name: 'USB-A',        count: '1×',  detail: 'USB-A — 再生', type: 'usb' },
            { name: 'USB-B',        count: '1×',  detail: 'USB-B — PC 34ch録音', type: 'usb' }],
  outputs: [{ name: 'XLR OUT',   count: '16×', detail: 'XLR バランス出力（OMNI 1–16）', type: 'xlr' },
            { name: 'USB-B',     count: '1×',  detail: 'USB-B — PC 34ch再生', type: 'usb' },
            { name: 'Headphone', count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['TouchFlow Operation。32chアナログ入力。48ミックスチャンネル。', '33フェーダー（モーターライズ）。TFシリーズ最大モデル。'],
  signal:  ['XLR IN ×32', '▶ TF5', 'OMNI OUT ×16', 'USB (34ch)'] },

{ id: 'yamaha-ql1', category: 'mixer', maker: 'Yamaha', model: 'QL1', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '16×', detail: 'Mic/Line コンボジャック（CH1–16、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '1×',  detail: 'Dante 64ch IN（Primary/Secondary RJ45）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '1×',  detail: 'Mini-YGDAIスロット — 拡張（最大16ch I/O）', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '8×', detail: 'XLR バランス OMNI OUT（1–8）', type: 'xlr' },
            { name: 'Dante',      count: '1×', detail: 'Dante 64ch OUT（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '1×', detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×', detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['QL1: 16ch XLR IN + Dante 64ch内蔵。コンパクトなQLシリーズ下位モデル。', '48ミックスチャンネル（mono×32 + stereo×8）。', 'StageMixアプリ（iPad）でリモートコントロール。'],
  signal:  ['XLR IN ×16', 'Dante 64ch', '▶ QL1', 'OMNI OUT ×8', 'Dante 64ch OUT'] },

{ id: 'yamaha-ql5', category: 'mixer', maker: 'Yamaha', model: 'QL5', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '32×', detail: 'Mic/Line コンボジャック（CH1–32、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '1×',  detail: 'Dante 64ch IN（Primary/Secondary RJ45）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '3×',  detail: 'Mini-YGDAIスロット ×3（各最大16ch）', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '16×', detail: 'XLR バランス OMNI OUT（1–16）', type: 'xlr' },
            { name: 'Dante',      count: '1×',  detail: 'Dante 64ch OUT（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '3×',  detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['QL5: 32ch XLR IN + Dante 64ch + Mini-YGDAIスロット×3。QLシリーズ上位。', '72ミックスチャンネル（mono×64 + stereo×8）。StageMix対応。'],
  signal:  ['XLR IN ×32', 'Dante 64ch', '▶ QL5', 'OMNI OUT ×16', 'Dante 64ch OUT'] },

{ id: 'yamaha-cl1', category: 'mixer', maker: 'Yamaha', model: 'CL1', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '16×', detail: 'Mic/Line コンボジャック（CH1–16、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '1×',  detail: 'Dante 64ch IN（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '3×',  detail: 'Mini-YGDAIスロット ×3（各最大16ch）', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '8×', detail: 'XLR バランス OMNI OUT（1–8）', type: 'xlr' },
            { name: 'Dante',      count: '1×', detail: 'Dante 64ch OUT（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '3×', detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×', detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['CLシリーズ最小モデル（8フェーダー左+8フェーダーCentralogic）。', 'Dante 64ch内蔵。Mini-YGDAIスロット×3。48ミックスチャンネル。', 'Rio3224-D2等のI/Oラックと組み合わせて大規模運用可能。'],
  signal:  ['XLR IN ×16', 'Dante 64ch', '▶ CL1', 'OMNI OUT ×8', 'Dante 64ch OUT'] },

{ id: 'yamaha-cl3', category: 'mixer', maker: 'Yamaha', model: 'CL3', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '24×', detail: 'Mic/Line コンボジャック（CH1–24、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '1×',  detail: 'Dante 64ch IN（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '3×',  detail: 'Mini-YGDAIスロット ×3', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '16×', detail: 'XLR バランス OMNI OUT（1–16）', type: 'xlr' },
            { name: 'Dante',      count: '1×',  detail: 'Dante 64ch OUT（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '3×',  detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['CLシリーズ中位モデル（16+8+2フェーダー構成）。24ch XLR IN / 16ch OUT。', 'Dante 64ch内蔵。Mini-YGDAIスロット×3。64ミックスチャンネル。'],
  signal:  ['XLR IN ×24', 'Dante 64ch', '▶ CL3', 'OMNI OUT ×16', 'Dante 64ch OUT'] },

{ id: 'yamaha-cl5', category: 'mixer', maker: 'Yamaha', model: 'CL5', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '32×', detail: 'Mic/Line コンボジャック（CH1–32、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '1×',  detail: 'Dante 64ch IN（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '3×',  detail: 'Mini-YGDAIスロット ×3', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '16×', detail: 'XLR バランス OMNI OUT（1–16）', type: 'xlr' },
            { name: 'Dante',      count: '1×',  detail: 'Dante 64ch OUT（Primary/Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '3×',  detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['CLシリーズフラッグシップ（16+8+8+2フェーダー）。32ch XLR IN / 16ch OUT。', 'Dante 64ch内蔵。Mini-YGDAIスロット×3。72ミックスチャンネル（mono64+stereo8）。', '内蔵メータブリッジ。'],
  signal:  ['XLR IN ×32', 'Dante 64ch', '▶ CL5', 'OMNI OUT ×16', 'Dante 64ch OUT'] },

{ id: 'yamaha-dm3', category: 'mixer', maker: 'Yamaha', model: 'DM3 / DM3S', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '8×', detail: 'Mic/Line コンボジャック（CH1–8、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '1×', detail: 'Dante 32ch IN（Primary RJ45）— DM3S: Dante + USB-C同時', type: 'lan' },
            { name: 'USB-C',        count: '1×', detail: 'USB-C — PC 10ch録音/再生（UAC対応）', type: 'usb' }],
  outputs: [{ name: 'XLR OUT',   count: '2×', detail: 'XLR バランスメイン OUT（L/R）', type: 'xlr' },
            { name: 'Dante',     count: '1×', detail: 'Dante 32ch OUT', type: 'lan' },
            { name: 'USB-C',     count: '1×', detail: 'USB-C — PC 10ch再生', type: 'usb' },
            { name: 'Headphone', count: '1×', detail: '3.5mm ヘッドフォン', type: 'mini' }],
  notes:   ['超コンパクトデジタルミキサー（6.5kg）。9インチタッチスクリーン。9フェーダー。', 'Dante内蔵（32×32）。USB-C オーディオIF機能。96kHz対応。', 'DM3S: Dante + USB-C同時使用可。TFシリーズの後継ポジション。'],
  signal:  ['XLR IN ×8', 'Dante 32ch', '▶ DM3', 'XLR OUT L/R', 'Dante 32ch OUT', 'USB-C'] },

{ id: 'yamaha-dm7', category: 'mixer', maker: 'Yamaha', model: 'DM7', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '32×', detail: 'Mic/Line コンボジャック（CH1–32、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '2×',  detail: 'Dante 128ch IN（Primary + Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '3×',  detail: 'Mini-YGDAIスロット ×3（各最大16ch）', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '16×', detail: 'XLR バランス OMNI OUT（1–16）', type: 'xlr' },
            { name: 'Dante',      count: '2×',  detail: 'Dante 128ch OUT（Primary + Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '3×',  detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×',  detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['CLシリーズ後継フラッグシップ。120ミックスチャンネル（mono×96 + stereo×12）。', 'Dante 128ch（Primary + Secondary）。Mini-YGDAIスロット×3。', '48 Mix Bus + 12 Matrix Bus + 2 Stereo Bus。'],
  signal:  ['XLR IN ×32', 'Dante 128ch', '▶ DM7', 'OMNI OUT ×16', 'Dante 128ch OUT'] },

{ id: 'yamaha-dm7-compact', category: 'mixer', maker: 'Yamaha', model: 'DM7 Compact', icon: '🎚️',
  inputs:  [{ name: 'XLR/Combo IN', count: '16×', detail: 'Mic/Line コンボジャック（CH1–16、+48V）', type: 'xlr' },
            { name: 'Dante',        count: '2×',  detail: 'Dante 128ch IN（Primary + Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI',   count: '3×',  detail: 'Mini-YGDAIスロット ×3', type: 'other' }],
  outputs: [{ name: 'XLR OUT',    count: '8×', detail: 'XLR バランス OMNI OUT（1–8）', type: 'xlr' },
            { name: 'Dante',      count: '2×', detail: 'Dante 128ch OUT（Primary + Secondary）', type: 'lan' },
            { name: 'Mini-YGDAI', count: '3×', detail: 'Mini-YGDAIスロット出力', type: 'other' },
            { name: 'Headphone',  count: '1×', detail: '1/4" TRS ヘッドフォン', type: 'trs' }],
  notes:   ['DM7のコンパクト版（16ch XLR IN / 8ch OUT）。72ミックスチャンネル。', 'Dante 128ch（Primary + Secondary）。Mini-YGDAIスロット×3。', '48 Mix Bus + 12 Matrix Bus + 2 Stereo Bus。'],
  signal:  ['XLR IN ×16', 'Dante 128ch', '▶ DM7 Compact', 'OMNI OUT ×8', 'Dante 128ch OUT'] },

// ══════════════════════════════════════════════════════════════
// FIELD MONITOR → now RECORDER / MONITOR (category: recorder)
// SmallHD / TVLogic kept here, category renamed
// ══════════════════════════════════════════════════════════════

{ id: 'smallhd-cine13', category: 'recorder', maker: 'SmallHD', model: 'Cine 13', icon: '🖥️',
  inputs:  [{ name: 'HDMI IN',    count: '2×', detail: 'HDMI 2.0 — up to 4K60p / HDR', type: 'hdmi' },
            { name: '12G-SDI IN', count: '2×', detail: '12G-SDI — up to 4K60p', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '2×', detail: '12G-SDI loop-through', type: 'sdi' },
            { name: '3.5mm',       count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['13.3" 2500 nit. Scopes: WFM/vectorscope/histogram/false color.', '3D LUT (33-pt). Loop-through all inputs.'],
  signal:  ['SDI/HDMI Source', '▶ Cine 13', 'SDI OUT ×2 (Loop)', 'HDMI OUT (Loop)'] },

{ id: 'tvlogic-svm130p', category: 'recorder', maker: 'TVLogic', model: 'SVM-130P', icon: '🖥️',
  inputs:  [{ name: 'HDMI IN',    count: '2×', detail: 'HDMI — up to 4K30p', type: 'hdmi' },
            { name: '12G-SDI IN', count: '2×', detail: '12G-SDI — up to 4K60p', type: 'sdi' }],
  outputs: [{ name: 'SDI OUT',  count: '1×', detail: '12G-SDI loop-through', type: 'sdi' },
            { name: 'HDMI OUT', count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['13.3" 1920×1080 IPS. Scopes. 3D LUT.'],
  signal:  ['SDI/HDMI Source', '▶ SVM-130P', 'SDI OUT (Loop)', 'HDMI OUT (Loop)'] },

// ── Blackmagic Video Assist ──────────────────────────────────

{ id: 'bm-video-assist-5-3g', category: 'recorder', maker: 'Blackmagic Design', model: 'Video Assist 5" 3G', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',   count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3G-SDI IN', count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI loop-through', type: 'sdi' }],
  notes:   ['5" タッチスクリーン。SD×1。ProRes/DNxHD 10-bit 4:2:2。', 'HDMI + SDI 同時入力モニタリング＆記録。'],
  signal:  ['Camera HDMI/SDI', '▶ Video Assist 5" 3G', 'HDMI/SDI OUT (Loop)'] },

{ id: 'bm-video-assist-7-3g', category: 'recorder', maker: 'Blackmagic Design', model: 'Video Assist 7" 3G', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',    count: '1×', detail: 'HDMI — up to 1080p60', type: 'hdmi' },
            { name: '3G-SDI IN',  count: '1×', detail: '3G-SDI — up to 1080p60', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',   count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '3G-SDI OUT', count: '1×', detail: '3G-SDI loop-through', type: 'sdi' },
            { name: 'mini-XLR IN',count: '2×', detail: 'バランスアナログ音声入力（+48V対応）', type: 'xlr' }],
  notes:   ['7" タッチスクリーン。SD×2（連続録画対応）。ProRes/DNxHD 10-bit 4:2:2。', 'mini-XLR音声入力あり（5インチモデルにはなし）。'],
  signal:  ['Camera HDMI/SDI', '▶ Video Assist 7" 3G', 'HDMI/SDI OUT (Loop)'] },

{ id: 'bm-video-assist-5-12g', category: 'recorder', maker: 'Blackmagic Design', model: 'Video Assist 5" 12G HDR', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',    count: '1×', detail: 'HDMI 2.0 — up to 4K60p / HDR', type: 'hdmi' },
            { name: '12G-SDI IN', count: '1×', detail: '12G-SDI — up to 4K60p', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '1×', detail: '12G-SDI loop-through', type: 'sdi' },
            { name: 'USB-C',       count: '1×', detail: 'USB-C 3.1 — 外部ドライブ記録 / ウェブカム出力', type: 'usb' }],
  notes:   ['5" 2500nit HDR タッチスクリーン。SD×1 + USB-C外部ドライブ記録。', 'ProRes/DNxHR 10-bit 4:2:2、Blackmagic RAW対応（対応カメラ）。', 'HDRスコープ（Waveform/RGB Parade/Vector/Histogram）、3D LUT。'],
  signal:  ['Camera HDMI/SDI (4K60p)', '▶ Video Assist 5" 12G HDR', 'HDMI/SDI OUT (Loop)', 'USB-C (External)'] },

{ id: 'bm-video-assist-7-12g', category: 'recorder', maker: 'Blackmagic Design', model: 'Video Assist 7" 12G HDR', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',     count: '1×', detail: 'HDMI 2.0 — up to 4K60p / HDR', type: 'hdmi' },
            { name: '12G-SDI IN',  count: '1×', detail: '12G-SDI — up to 4K60p', type: 'sdi' },
            { name: 'mini-XLR IN', count: '2×', detail: 'バランスアナログ音声入力（+48V対応）', type: 'xlr' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '1×', detail: '12G-SDI loop-through', type: 'sdi' },
            { name: 'USB-C',       count: '1×', detail: 'USB-C 3.1 — 外部ドライブ記録 / ウェブカム出力', type: 'usb' },
            { name: '3.5mm',       count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['7" 2500nit HDR タッチスクリーン。SD×2（連続録画）+ USB-C外部ドライブ。', 'mini-XLR音声入力 ×2（+48Vファンタム）。', 'ProRes/DNxHR 10-bit 4:2:2、Blackmagic RAW。HDRスコープ、3D LUT。'],
  signal:  ['Camera HDMI/SDI (4K60p)', '▶ Video Assist 7" 12G HDR', 'HDMI/SDI OUT (Loop)', 'USB-C (External)'] },

// ── Atomos ───────────────────────────────────────────────────

{ id: 'atomos-ninja-v', category: 'recorder', maker: 'Atomos', model: 'Ninja V', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN', count: '1×', detail: 'HDMI 2.0 — up to 4K60p / RAW (対応カメラ)', type: 'hdmi' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: 'USB-C',    count: '1×', detail: 'USB-C — SSD記録・電源', type: 'usb' },
            { name: '3.5mm',    count: '1×', detail: 'Headphone / 音声出力', type: 'mini' }],
  notes:   ['5" 1000nit タッチスクリーン。HDMIのみ（SDIなし）。', 'ProRes RAW（対応カメラのHDMI RAW出力）、ProRes/DNxHR。', 'SSDに記録（AtomX SSDmini、2.5" SSD）。スコープ・LUT・フォーカスピーキング。'],
  signal:  ['Camera HDMI', '▶ Ninja V', 'HDMI OUT (Loop)', 'SSD Record'] },

{ id: 'atomos-ninja-tx', category: 'recorder', maker: 'Atomos', model: 'Ninja TX', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',    count: '1×', detail: 'HDMI 2.0 — up to 8Kp30 / 4Kp60 / RAW', type: 'hdmi' },
            { name: '12G-SDI IN', count: '1×', detail: '12G-SDI — up to 4Kp60 / RAW over SDI', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI loop-through / HDMI→SDI クロスコンバート', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '1×', detail: 'SDI loop-through / SDI→HDMI クロスコンバート', type: 'sdi' },
            { name: 'USB-C',       count: '2×', detail: 'CFexpress Type B記録 / USB外部ストレージ', type: 'usb' }],
  notes:   ['5" 1500nit タッチスクリーン。HDMI + 12G-SDI 両対応（Ninja Vの上位）。', 'ProRes RAW up to 8Kp30。CFexpress Type B + USB-C外部ストレージ。', 'カメラコントロール（USB-C）、Wi-Fi、Camera to Cloud (ATOMOSphere)、NDI 6。', 'HDMI↔SDI クロスコンバート対応。AtomOS Linux。'],
  signal:  ['Camera HDMI/SDI', '▶ Ninja TX', 'HDMI/SDI OUT (Loop/CrossConvert)', 'CFexpress/SSD Record'] },

{ id: 'atomos-shogun-7', category: 'recorder', maker: 'Atomos', model: 'Shogun 7', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',    count: '1×', detail: 'HDMI 2.0 — up to 4Kp60 / RAW', type: 'hdmi' },
            { name: '12G-SDI IN', count: '4×', detail: '12G-SDI — Quad Link / Dual Link / Single Link', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI loop-through', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '1×', detail: '12G-SDI loop-through', type: 'sdi' },
            { name: 'XLR',         count: '2×', detail: 'XLR IN/OUT ブレイクアウトケーブル（+48V）', type: 'xlr' },
            { name: '3.5mm',       count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['7" 1500nit タッチスクリーン。SDI×4入力（マルチカムスイッチャー機能）。', 'ProRes RAW up to 5.7Kp30 / 4Kp120。2.5" SSD/HDD記録。', '4ch SDI入力でISO記録しながらライブスイッチング可能。', 'HDMI↔SDI クロスコンバート、Genlock/LTC入力。'],
  signal:  ['Camera HDMI + SDI×4', '▶ Shogun 7', 'HDMI/SDI OUT (Loop)', 'SSD Record (ISO×4)'] },

{ id: 'atomos-shogun-classic', category: 'recorder', maker: 'Atomos', model: 'Shogun Classic', icon: '⏺️',
  inputs:  [{ name: 'HDMI IN',    count: '1×', detail: 'HDMI — up to 4Kp60', type: 'hdmi' },
            { name: '12G-SDI IN', count: '4×', detail: '12G-SDI — Quad/Dual/Single Link', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT',    count: '1×', detail: 'HDMI loop-through / スイッチャー出力', type: 'hdmi' },
            { name: '12G-SDI OUT', count: '1×', detail: 'SDI loop-through / スイッチャー出力', type: 'sdi' },
            { name: 'XLR',         count: '1×', detail: 'XLR 2pinアナログ音声 IN/OUT', type: 'xlr' },
            { name: '3.5mm',       count: '1×', detail: 'Headphone', type: 'mini' }],
  notes:   ['7.2" 3000nit HDR タッチスクリーン。SDI×4でライブスイッチャー＋ISO記録（×4 + PGM）。', 'ProRes / DNxHR。SSDmini記録。Genlock/LTC via BNC。', 'Shogun 7後継のAtomOS世代モデル。'],
  signal:  ['HDMI + SDI×4', '▶ Shogun Classic', 'HDMI/SDI OUT', 'SSDmini Record'] },

// ══════════════════════════════════════════════════════════════
// DISTRIBUTION / ROUTING / CONVERTER
// ══════════════════════════════════════════════════════════════

{ id: 'videohub-smart-12x12', category: 'routing', maker: 'Blackmagic Design', model: 'Smart Videohub 12×12', icon: '🔀',
  inputs:  [{ name: 'SDI IN', count: '12×', detail: '3G-SDI, up to 1080p60', type: 'sdi' }],
  outputs: [{ name: 'SDI OUT', count: '12×', detail: '3G-SDI, up to 1080p60', type: 'sdi' },
            { name: 'LAN',     count: '1×',  detail: 'Ethernet — Videohub Control', type: 'lan' }],
  notes:   ['12×12 SDI matrix router. Videohub Control software.'],
  signal:  ['SDI IN ×12', '▶ Smart Videohub 12×12', 'SDI OUT ×12'] },

{ id: 'bm-sdi-distrib', category: 'routing', maker: 'Blackmagic Design', model: 'Mini Converter SDI Distribution', icon: '🔀',
  inputs:  [{ name: 'SDI IN', count: '1×', detail: '3G-SDI, up to 1080p60', type: 'sdi' }],
  outputs: [{ name: 'SDI OUT', count: '8×', detail: '3G-SDI reclocked (×8)', type: 'sdi' }],
  notes:   ['1-in/8-out distribution amp. Reclocked.'],
  signal:  ['SDI Source', '▶ SDI Distribution', 'SDI OUT ×8'] },

{ id: 'bm-hdmi-to-sdi', category: 'routing', maker: 'Blackmagic Design', model: 'Mini Converter HDMI to SDI 6G', icon: '🔀',
  inputs:  [{ name: 'HDMI IN', count: '1×', detail: 'HDMI 2.0 — up to 4K30p / 1080p60', type: 'hdmi' }],
  outputs: [{ name: '6G-SDI OUT', count: '2×', detail: '6G-SDI — up to 4K30p (dual output)', type: 'sdi' }],
  notes:   ['Converts HDMI → dual SDI. Camera HDMI → SDI routing.'],
  signal:  ['Camera HDMI', '▶ HDMI→SDI 6G', '6G-SDI OUT ×2'] },

{ id: 'bm-sdi-to-hdmi', category: 'routing', maker: 'Blackmagic Design', model: 'Mini Converter SDI to HDMI 6G', icon: '🔀',
  inputs:  [{ name: '6G-SDI IN', count: '1×', detail: '6G-SDI — up to 4K30p / 1080p60', type: 'sdi' }],
  outputs: [{ name: 'HDMI OUT', count: '1×', detail: 'HDMI 2.0 — monitor output', type: 'hdmi' },
            { name: 'SDI OUT',  count: '1×', detail: '6G-SDI loop-through', type: 'sdi' },
            { name: 'XLR OUT',  count: '2×', detail: 'Balanced analog audio de-embed', type: 'xlr' }],
  notes:   ['SDI → HDMI for displays. Audio de-embed. SDI loop.'],
  signal:  ['SDI Source', '▶ SDI→HDMI 6G', 'HDMI OUT', 'XLR OUT', 'SDI OUT (loop)'] },

]; // end DEVICES
